version: '3.8'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=contactquality
      - MYSQL_ROOT_PASSWORD=T@mso007
    ports:
      - '3306:3306'
#     volumes:
#       - db:/var/lib/mysql
# volumes:
#   db:
#     driver: local
